/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.carhire.rentals;

import dataentities.Booking;
import dataentities.Branch;
import dataentities.Customer;
import java.util.Vector;
import javax.swing.table.AbstractTableModel;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;

/**
 *
 * @author Kabaji Egara
 */
public class CustomerBookingInfo extends javax.swing.JPanel {
    static BookingTableModel bookings = new BookingTableModel();
    

    public static void displayBookings(Customer customer) {
        
        CustomerBookingInfo dialog = new CustomerBookingInfo();
        dialog.jTable1.setModel(bookings);
        bookings.getData().clear();
        bookings.getData().addAll(DataModel.getCustomerBookings(customer));
        System.out.print("Just fetched the datamodel");
        bookings.fireTableDataChanged();
        DialogDescriptor d = new DialogDescriptor(dialog,"View Bookings & Make Extensions");
        System.out.println("Displaying");
        if(DialogDisplayer.getDefault().notify(d)==DialogDescriptor.OK_OPTION){
            Booking book = BookingExtensionDialog.editBooking(bookings.getRow(jTable1.getSelectedRow()));
            if(book!=null){
                DataModel.updateBooking(book);
                bookings.fireTableDataChanged();
            }
        }
        
        //adminif(DialogDisplayer.getDefault().notify(d)==DialogDescriptor.OK_OPTION)
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    static void showBranchOrders(Branch branch, long branchid) {
        CustomerBookingInfo dialog = new CustomerBookingInfo();
        dialog.jTable1.setModel(bookings);
        bookings.getData().clear();
        bookings.getData().addAll(DataModel.getBranchBookings(branchid));
        System.out.print("Just fetched the datamodel");
        bookings.fireTableDataChanged();
        DialogDescriptor d = new DialogDescriptor(dialog,"View Bookings & Make Extensions");
        System.out.println("Displaying");
        DialogDisplayer.getDefault().notify(d);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * Creates new form CustomerBookingInfo
     */
    public CustomerBookingInfo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public static final class BookingTableModel extends AbstractTableModel{
        public String[] columns = {"Vehicle","Date Rented","Date Returned","Price"};
        public Vector<Booking> data = new Vector<Booking>();
        
        public Booking getRow(int row){
            return data.get(row);
        }

        @Override
        public int getRowCount() {
            return data.size();
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public int getColumnCount() {
            return columns.length;
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Booking booking = data.get(rowIndex);
            switch(columnIndex){
                case 0:
                    return booking.getVehicle().getDescription();
                case 1:
                    return booking.getDateRented();
                case 2:
                    return booking.getDateToReturn();
                case 3:
                    return booking.getPrice();
                    
            }
            return "";
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
        
        @Override
        public String getColumnName(int col){
            return columns[col];
        }
        
        public Vector<Booking> getData(){
            return data;
        }
        
    }

}
